services:
  - type: web
    name: fsd-student-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URL
        scope: build
      - key: MONGO_URL
        scope: runtime
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        scope: runtime
      - key: PORT
        value: 5000
